FROM node:18-alpine as builder

WORKDIR /app
# Install dependencies first to take advantage of layer caching
COPY package*.json ./
RUN npm install
# Copy everything else and run the dev server
COPY . .
RUN npm run build

FROM nginx:stable-alpine  as runner
COPY --from=builder /app/build /usr/share/nginx/html
COPY --from=builder /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]