FROM node:18-alpine
WORKDIR /app

# Copy backend app files and install production deps
COPY package*.json ./
RUN npm install
COPY . .

# Create uploads directory
RUN mkdir -p /app/uploads
EXPOSE 4000
ENV NODE_ENV=DEVELOPEMENT

CMD ["nodemon", "backend/server.js"]
